### ISSUE TITLE
Datetime not reset on submit

### ISSUE THREAD

**Issue by elie222** [aldeed/meteor-autoform-bs-datetimepicker#10]
When I submit a form, the form gets reset and the datetime input looks like it's reset (it's blank in the input in the form), but if I retry submit the form without the datetime filled in, it will use the previous value for this input.
What should really happen is an error, because the field is set as required, but because it remembers the previous value, there's no error, it just submits.

**Comment by Asparagirl** [comment]
+1

**Comment by damonmcminn** [comment]
+1

The issue is the input is reset but not the value set by the input.

@aldeed I've scoured source for this and `meteor-autoform` and am unclear where form state is being stored (object? Map?) and how the other form values are reset but not the values associated with the datetime inputs.

I'd love to investigate further and make PR, just need a pointer in the right direction.

Cheers!

**Comment by shkomg** [comment]
+1

**Comment by aldeed** [comment]
Closing all issues. The plugin was a proof of concept which others have forked and made better alternatives.
